# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/marks.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wMarks(object):
    def setupUi(self, wMarks):
        wMarks.setObjectName("wMarks")
        wMarks.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(wMarks)
        self.centralwidget.setObjectName("centralwidget")
        self.cbSquad = QtWidgets.QComboBox(self.centralwidget)
        self.cbSquad.setGeometry(QtCore.QRect(10, 10, 231, 35))
        self.cbSquad.setObjectName("cbSquad")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 1261, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.twStudent = QtWidgets.QWidget()
        self.twStudent.setObjectName("twStudent")
        self.twStudentInfo = QtWidgets.QTabWidget(self.twStudent)
        self.twStudentInfo.setGeometry(QtCore.QRect(10, 45, 1240, 510))
        self.twStudentInfo.setObjectName("twStudentInfo")
        self.tabGeneralInfo = QtWidgets.QWidget()
        self.tabGeneralInfo.setObjectName("tabGeneralInfo")
        self.gbName = QtWidgets.QGroupBox(self.tabGeneralInfo)
        self.gbName.setGeometry(QtCore.QRect(10, 10, 171, 131))
        self.gbName.setBaseSize(QtCore.QSize(50, 50))
        self.gbName.setAutoFillBackground(False)
        self.gbName.setFlat(True)
        self.gbName.setCheckable(False)
        self.gbName.setObjectName("gbName")
        self.lLast = QtWidgets.QLabel(self.gbName)
        self.lLast.setGeometry(QtCore.QRect(10, 30, 181, 21))
        self.lLast.setObjectName("lLast")
        self.lFirst = QtWidgets.QLabel(self.gbName)
        self.lFirst.setGeometry(QtCore.QRect(10, 60, 181, 21))
        self.lFirst.setObjectName("lFirst")
        self.lMiddle = QtWidgets.QLabel(self.gbName)
        self.lMiddle.setGeometry(QtCore.QRect(10, 90, 181, 21))
        self.lMiddle.setObjectName("lMiddle")
        self.gbDiscipline = QtWidgets.QGroupBox(self.tabGeneralInfo)
        self.gbDiscipline.setGeometry(QtCore.QRect(10, 140, 171, 91))
        self.gbDiscipline.setBaseSize(QtCore.QSize(50, 50))
        self.gbDiscipline.setAutoFillBackground(False)
        self.gbDiscipline.setFlat(True)
        self.gbDiscipline.setCheckable(False)
        self.gbDiscipline.setObjectName("gbDiscipline")
        self.lBad = QtWidgets.QLabel(self.gbDiscipline)
        self.lBad.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.lBad.setObjectName("lBad")
        self.lGood = QtWidgets.QLabel(self.gbDiscipline)
        self.lGood.setGeometry(QtCore.QRect(10, 60, 111, 21))
        self.lGood.setObjectName("lGood")
        self.lBadCnt = QtWidgets.QLabel(self.gbDiscipline)
        self.lBadCnt.setGeometry(QtCore.QRect(120, 30, 41, 21))
        self.lBadCnt.setObjectName("lBadCnt")
        self.lGoodCnt = QtWidgets.QLabel(self.gbDiscipline)
        self.lGoodCnt.setGeometry(QtCore.QRect(120, 60, 41, 21))
        self.lGoodCnt.setObjectName("lGoodCnt")
        self.gbAverage = QtWidgets.QGroupBox(self.tabGeneralInfo)
        self.gbAverage.setGeometry(QtCore.QRect(180, 10, 321, 210))
        self.gbAverage.setObjectName("gbAverage")
        self.tAverage = QtWidgets.QTableView(self.gbAverage)
        self.tAverage.setGeometry(QtCore.QRect(10, 30, 250, 171))
        self.tAverage.setObjectName("tAverage")
        self.twStudentInfo.addTab(self.tabGeneralInfo, "")
        self.tabCommand = QtWidgets.QWidget()
        self.tabCommand.setObjectName("tabCommand")
        self.bAddDuty = QtWidgets.QPushButton(self.tabCommand)
        self.bAddDuty.setGeometry(QtCore.QRect(10, 420, 100, 35))
        self.bAddDuty.setObjectName("bAddDuty")
        self.tDuties = QtWidgets.QTableView(self.tabCommand)
        self.tDuties.setGeometry(QtCore.QRect(5, 5, 1000, 400))
        self.tDuties.setObjectName("tDuties")
        self.lDuties = QtWidgets.QLabel(self.tabCommand)
        self.lDuties.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.lDuties.setObjectName("lDuties")
        self.twStudentInfo.addTab(self.tabCommand, "")
        self.tabDiscipline = QtWidgets.QWidget()
        self.tabDiscipline.setObjectName("tabDiscipline")
        self.bAddPenalty = QtWidgets.QPushButton(self.tabDiscipline)
        self.bAddPenalty.setGeometry(QtCore.QRect(10, 420, 100, 35))
        self.bAddPenalty.setObjectName("bAddPenalty")
        self.tPenalties = QtWidgets.QTableView(self.tabDiscipline)
        self.tPenalties.setGeometry(QtCore.QRect(5, 5, 1000, 400))
        self.tPenalties.setObjectName("tPenalties")
        self.lPenalties = QtWidgets.QLabel(self.tabDiscipline)
        self.lPenalties.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.lPenalties.setObjectName("lPenalties")
        self.bAddPromotion = QtWidgets.QPushButton(self.tabDiscipline)
        self.bAddPromotion.setGeometry(QtCore.QRect(120, 420, 111, 35))
        self.bAddPromotion.setObjectName("bAddPromotion")
        self.twStudentInfo.addTab(self.tabDiscipline, "")
        self.tabEvents = QtWidgets.QWidget()
        self.tabEvents.setObjectName("tabEvents")
        self.tEvents = QtWidgets.QTableView(self.tabEvents)
        self.tEvents.setGeometry(QtCore.QRect(5, 5, 1000, 400))
        self.tEvents.setObjectName("tEvents")
        self.lEvents = QtWidgets.QLabel(self.tabEvents)
        self.lEvents.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.lEvents.setObjectName("lEvents")
        self.bAddEvent = QtWidgets.QPushButton(self.tabEvents)
        self.bAddEvent.setGeometry(QtCore.QRect(10, 420, 100, 35))
        self.bAddEvent.setObjectName("bAddEvent")
        self.twStudentInfo.addTab(self.tabEvents, "")
        self.tabAllMarks = QtWidgets.QWidget()
        self.tabAllMarks.setObjectName("tabAllMarks")
        self.bMarksInputStudent = QtWidgets.QPushButton(self.tabAllMarks)
        self.bMarksInputStudent.setGeometry(QtCore.QRect(10, 0, 120, 35))
        self.bMarksInputStudent.setObjectName("bMarksInputStudent")
        self.tMarksStudent = QtWidgets.QTableView(self.tabAllMarks)
        self.tMarksStudent.setEnabled(False)
        self.tMarksStudent.setGeometry(QtCore.QRect(10, 40, 971, 401))
        self.tMarksStudent.setObjectName("tMarksStudent")
        self.bAddDate = QtWidgets.QPushButton(self.tabAllMarks)
        self.bAddDate.setGeometry(QtCore.QRect(130, 0, 160, 35))
        self.bAddDate.setObjectName("bAddDate")
        self.twStudentInfo.addTab(self.tabAllMarks, "")
        self.cbStudent = QtWidgets.QComboBox(self.twStudent)
        self.cbStudent.setGeometry(QtCore.QRect(5, 5, 200, 35))
        self.cbStudent.setObjectName("cbStudent")
        self.cbStudent.addItem("")
        self.cbStudent.setItemText(0, "")
        self.tabWidget.addTab(self.twStudent, "")
        self.twSubject = QtWidgets.QWidget()
        self.twSubject.setObjectName("twSubject")
        self.cbSubject = QtWidgets.QComboBox(self.twSubject)
        self.cbSubject.setGeometry(QtCore.QRect(10, 0, 200, 35))
        self.cbSubject.setObjectName("cbSubject")
        self.cbSubject.addItem("")
        self.cbSubject.setItemText(0, "")
        self.bMarksInputSubject = QtWidgets.QPushButton(self.twSubject)
        self.bMarksInputSubject.setGeometry(QtCore.QRect(220, 0, 120, 35))
        self.bMarksInputSubject.setObjectName("bMarksInputSubject")
        self.tMarksSubject = QtWidgets.QTableView(self.twSubject)
        self.tMarksSubject.setEnabled(False)
        self.tMarksSubject.setGeometry(QtCore.QRect(10, 40, 981, 481))
        self.tMarksSubject.setObjectName("tMarksSubject")
        self.tSquadAverage = QtWidgets.QTableView(self.twSubject)
        self.tSquadAverage.setGeometry(QtCore.QRect(1000, 330, 241, 192))
        self.tSquadAverage.setObjectName("tSquadAverage")
        self.tabWidget.addTab(self.twSubject, "")
        wMarks.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wMarks)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 29))
        self.menubar.setObjectName("menubar")
        self.menutest = QtWidgets.QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        wMarks.setMenuBar(self.menubar)
        self.menubar.addAction(self.menutest.menuAction())

        self.retranslateUi(wMarks)
        self.tabWidget.setCurrentIndex(1)
        self.twStudentInfo.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(wMarks)

    def retranslateUi(self, wMarks):
        _translate = QtCore.QCoreApplication.translate
        wMarks.setWindowTitle(_translate("wMarks", "Электронный журнал"))
        self.gbName.setTitle(_translate("wMarks", "ФИО"))
        self.lLast.setText(_translate("wMarks", "TextLabel"))
        self.lFirst.setText(_translate("wMarks", "TextLabel"))
        self.lMiddle.setText(_translate("wMarks", "TextLabel"))
        self.gbDiscipline.setTitle(_translate("wMarks", "Дисциплина"))
        self.lBad.setText(_translate("wMarks", "Взысканий:"))
        self.lGood.setText(_translate("wMarks", "Поощрений:"))
        self.lBadCnt.setText(_translate("wMarks", "0"))
        self.lGoodCnt.setText(_translate("wMarks", "0"))
        self.gbAverage.setTitle(_translate("wMarks", "Успеваемость"))
        self.twStudentInfo.setTabText(self.twStudentInfo.indexOf(self.tabGeneralInfo), _translate("wMarks", "Информация"))
        self.bAddDuty.setText(_translate("wMarks", "Добавить"))
        self.lDuties.setText(_translate("wMarks", "У студента нет дежурств"))
        self.twStudentInfo.setTabText(self.twStudentInfo.indexOf(self.tabCommand), _translate("wMarks", "Дежурства"))
        self.bAddPenalty.setText(_translate("wMarks", "Взыскание"))
        self.lPenalties.setText(_translate("wMarks", "У студента нет поощрений и взысканий"))
        self.bAddPromotion.setText(_translate("wMarks", "Поощрение"))
        self.twStudentInfo.setTabText(self.twStudentInfo.indexOf(self.tabDiscipline), _translate("wMarks", "Дисциплина"))
        self.lEvents.setText(_translate("wMarks", "Студент не участвовал в мероприятиях"))
        self.bAddEvent.setText(_translate("wMarks", "Добавить"))
        self.twStudentInfo.setTabText(self.twStudentInfo.indexOf(self.tabEvents), _translate("wMarks", "Мероприятия"))
        self.bMarksInputStudent.setText(_translate("wMarks", "Ввод оценок"))
        self.bAddDate.setText(_translate("wMarks", "Добавление даты"))
        self.twStudentInfo.setTabText(self.twStudentInfo.indexOf(self.tabAllMarks), _translate("wMarks", "Все оценки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twStudent), _translate("wMarks", "Студент"))
        self.bMarksInputSubject.setText(_translate("wMarks", "Ввод оценок"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twSubject), _translate("wMarks", "Журнал взвода"))
        self.menutest.setTitle(_translate("wMarks", "Меню"))

